#!/usr/bin/perl

$in = 0;
$l = "";
$n=0;

#print "<div class=\"row-fluid\">\n";
print "Name|Labels|Architecture|Type|Default|Description\n";
while(<>) {
    if(/  (product|lp64_product|product_pd|product_rw|manageable|diagnostic|develop)\(/) { 
        chomp;
        $in = 1;
        $l = $_;
        if(/\" ?\)/) {
            $in = 0;
            p($_);
        }
    } elsif ($in == 1) { if(/\"\)/) { $in = 0;
            $_ = $l . $_;
            p($_);
        } else { chomp;
            $l = $l . $_;
        }
    }
}
#print "</div>\n";


sub clean
{
    $_ = $_[0];
    s/"/ /g;
    s/\s+\\\s+/ /g;
    s/\)\s*\\?$/ /g;
    s/  ([a-zA-Z0-9_]*?)\((.*?), ?(.*?), ?(.*?),/$1|$3|$2|$4|/g;
    s/  ([a-zA-Z0-9_]*?)\((.*?), ?(.*?),/$1|$3|$2|---Platform dependent---|/g;
    s/^ //g;
    s/\| +/|/g;
    s/\|\|/|--empty value--|/g;
    s/\|bool\|/|Boolean|/g;
    s/\|uintx\|/|Positive Integer|/g;
    s/\|intx\|/|Integer|/g;
    s/\|double\|/|Double|/g;
    s/\|ccstrlist\|/|String list (comma separated)|/g;
    s/\|ccstr\|/|String|/g;
    s/&/&amp;/g;
    s/</&lt;/g;
    s/>/&gt;/g;
    s/(\d+)\*([GMK])/$1$2/g;
    s/NULL/null/g;
    s/NOT_LP64\((.*?)\) LP64_ONLY\((.*?)\)/$1 for 32-bits arch, $2 for 64-bits arch/g;
    s/max_uintx/0xFFFFFFFF for 32-bits arch, 0xFFFFFFFFFFFFFFFF for 64-bits arch/g;
    s/ScaleForWordSize\((.*?)\)/$1/g;
    s# /\*ms\*/##g;

    return $_;
}


sub p
{
    $_ = clean($_[0]);

    if(/(.*)\|(.*)\|(.*)\|(.*)\|(.*)/){
        $op = $1;
        $na = $2;
        $ty = $3;
        $df = $4;
        $de = $5;

        if($op =~ /lp64/) {
            @arch = ("64-bits");
        } else {
            @arch = ("32-bits", "64-bits");
        }

        $op =~ s/lp64_product|product_pd|product_rw|manageable|product/Product/g;
        $op =~ s/diagnostic/Diagnostic/g;
        $op =~ s/develop/Develop/g;

        cesve($op, $na, $ty, $df, $de, \@arch);
    }


    #if($n++ == 2) {print "</div>\n<div class=\"row-fluid\">\n";
    #    $n=0;
    #}
}

sub cards
{
    $arch = join("</span> <span class='label arch'>", @{$_[5]});
    print "<div class='span4 well'><h3>$_[1]</h3><p><strong>Type : </strong>$_[2]</p><p><strong>Default value : </strong>$_[3]</p><p>$_[4]</p><p><span class='label $_[0]'>$_[0]</span> <span class='label arch'>$arch</span></p></div>\n";
}

sub lines
{
    $arch = join("</span> <span class='label arch'>", @{$_[5]});
    print "<div class='span12 well jvm-option'><p class='pull-right option-category'><span class='label $_[0]'>$_[0]</span> <span class='label arch'>$arch</span></p><p class='pull-right option-type'><strong>Type : </strong>$_[2]</p><p class='pull-right option-default-value'><strong>Default value : </strong>$_[3]</p><h3>$_[1]</h3><p>$_[4]</p></div>\n";
}
# NAME LABEL ARCH TYPE DEFAULT DESCR
sub cesve
{
    $arch = join(",", @{$_[5]});
    print "$_[1]|$_[0]|$arch|$_[2]|$_[3]|$_[4]\n";
}

sub json
{
    $_=$_[0];
    s#(.*)\|(.*)\|(.*)\|(.*)#  { "name": "$1", "type": "$2", "default": "$3", "description": "$4", "tags": [ { "tag": "Unknown" } ] },#g;
    print "$_\n";

}


